# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f084e6f50e7b6edf3f778fd1c28d94ebd2649f212a1d2620d2bdd83ce94e0d2f7b50e80217eeeb2f8712932d4046c9120f0b6709babf119e3fa977faf7fff3d6

test:
  secret_key_base: 1447251886fed0620529b8bedd6f38ceeb8817fb94bc20eb7b172aea8c8c0e347183bdc2a7bc1a66a98140b86ac488657a6ff1c69118b6c42b9fb258f3c453e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
